name: medical-app

services:

  db:
    image: postgres:16.3-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${HOST_DB_PORT}:5432
    expose:
      - "5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
    entrypoint: ["./docker_entrypoint.sh"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_ECHO=${DATABASE_ECHO}
      - DB_MIGRATION_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
