"""init

Revision ID: 2dd0ce5624b5
Revises: 
Create Date: 2024-07-29 17:11:46.703688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2dd0ce5624b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinician',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('registration_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication',
    sa.Column('code_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strength_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('strength_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('form', sa.Enum('powder', 'tablet', 'capsule', 'syrup', name='medicationform'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicationrequest',
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'on-hold', 'cancelled', 'completed', name='medicationrequeststatus'), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('prescribed_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinician.id'], ),
    sa.ForeignKeyConstraint(['medication_id'], ['medication.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicationrequest_prescribed_date'), 'medicationrequest', ['prescribed_date'], unique=False)
    op.create_index(op.f('ix_medicationrequest_status'), 'medicationrequest', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicationrequest_status'), table_name='medicationrequest')
    op.drop_index(op.f('ix_medicationrequest_prescribed_date'), table_name='medicationrequest')
    op.drop_table('medicationrequest')
    op.drop_table('patient')
    op.drop_table('medication')
    op.drop_table('clinician')
    # ### end Alembic commands ###
